### ISSUE TITLE
Including ISIG on the info sent to Urchin Pebble face *Not a bug, development request

### ISSUE THREAD

**Issue by tuzoenduro** [pazaan/600SeriesAndroidUploader#236]
Can the ISIG number, or the ISIG/BG be sent to the Urchin pebble face? It is always good to have this in mind whenever calibrating, so as not to do it if it is outside of range. Getting to the ISIG involves many clicks in the pump, it would be helpful if it was available otherwise.

#### Your Environment
Medtronic 640g with a Pebble Time

#### Brief Explanation of Issue
I still have empty space on the watchface, the ISIG number would be a great addition.

#### Severity Score
1. This is not urgent but would be a nice have

**Comment by Pogman** [comment]
Unfortunately the ISIG value is not generally available every time a poll runs and only exists as part of a cgm history request . To keep things efficient history requests are only done on an a as-needed basis.

**Comment by tuzoenduro** [comment]
aww shucks... ok, It would have been nice though. Thanks!

**Comment by Pogman** [comment]
There is a feature coming to the next version that will estimate SGV's even when a calibration is missed and the pump shows no value (even after end of life). Handy if you feel like you need to wait due to SG moving around or in a bad range for cal. Might be helpful..

**Comment by tuzoenduro** [comment]
Oups, closed this before your answer.. Even though the point is closed, no need to keep things open polluting the list.

I had seen about the estimated SGV. I also saw the possibility of making "auto" calibrations based on the existing values. Both would be helpful additions.

**Comment by Pogman** [comment]
Had another look at this as most of the work done for the sgv estimator handles the isig.  When enabled and CGM is available but no SGV is received from the pump this will request cgm history and get the isig.

What this means is isig will be shown via the pump status pill in nightscout as needed. From an efficiency pov due to history requests it is reasonably minimal ie. cgm errors and warmup mostly, anyhow it's disabled by default.

Not looked at Urchin yet but for that it will only be available via the uploaders in-built Urchin support.

![ns-report-isig](https://user-images.githubusercontent.com/7413594/47607802-a52e1400-da1c-11e8-8cee-8e852fbd6dc1.JPG)
![ns-report-isig-5](https://user-images.githubusercontent.com/7413594/47607803-abbc8b80-da1c-11e8-81ee-507b6607253c.JPG)
![ns-report-isig-3](https://user-images.githubusercontent.com/7413594/47607810-c68f0000-da1c-11e8-9e84-a70764d5f3f4.JPG)
![ns-report-isig-4](https://user-images.githubusercontent.com/7413594/47607814-cdb60e00-da1c-11e8-9012-69534efa5d08.JPG)

**Comment by tuzoenduro** [comment]
Wow! Awesome

**Comment by Pogman** [comment]
Turns out seeing isig as a single value is not much help really and you need to see it in context to preceding isig values.

Taking this a bit further, several isig are reported along with rates of change and a gain calculation over 30 minutes to show if rising, falling, steady etc.

![ns-report-isig-6](https://user-images.githubusercontent.com/7413594/47730570-5c639e80-dc5a-11e8-9a58-6dae991ba4c0.JPG)

**Comment by geecolux** [comment]
If possible, I think can be useful read a parallel graph with isig. So I can read isig and sgv and when sgv is not available read only isig.

**Comment by shawnbissell** [comment]
I really like this feature! It works very well when my T1D child needs calibration but BG is swinging rapidly up or down. We are able to time calibration right when the isig value levels off.

One enhancement to this would be to have a one off poll ( or short period ... like 4 hours) where the isig values are shown in the uploader and NS. We often have a period of time right after the first calibration of a new sensor where the Enlite isig values are crazy low and we want to wait till they are normal before doing the second calibration (approx 4-8 hours after first one ... usually 1am : ( )

**Comment by Pogman** [comment]
Cool, good to see it having some use!

From my notes...

If the ISIG feature is triggered due to a sensor error then use a minimum cutoff time to keep showing these values rather then only during the sensor error state. This means it could run for the next 30 mins after the first time it shows.

Auto show the ISIG when SG within a certain range ie. <80 or <70 

Auto show based on SG jumpiness ie something like 100 > 110 > 90 > 105 would  trigger

If <12 hours on a new sensor show the ISIG or always show until 2nd calibration

Cal nearly due (next 60 mins?) - recommend best time based on steady sgv? auto read the ISIG for fluctuations? send PO system alert for this ready/best time recommendation?

Unfortunatly the only way of showing these in NS is tagging on to the pump status pill which is already quite cramped.

It may be usful to do analysis of the isig data based on sensor age and give a recomendation, first 24 hours on a new sensor can go from great to looking dead specially if there is any truma from insertion like a bleed.

**Comment by shawnbissell** [comment]
Awesome any and all of those features would be very helpful to me personally and anybody still having to deal with the Enlite calibration inaccuracies and sensor failure cases. I can't speak for the Guardian sensor's but I'm sure there have similar problems. 

Just today we had a sensor go crazy and swing wildly from an SG of 14.7 mmol/L to 3.2 in a matter of minutes causing a suspend on low ... finger check show'd BG 15.5! I looked at the ISIG history on the pump and as expected it was showing very low values (under 10) which would have caused a calibration to fail for sure. (Side note: some of the values where in brackets like (20.5) not sure why though)

Also right now I'm waiting for the second calibration window and although I can see the SG level off and a flat right arrow, if the isig value is < 35 with a BG of approx 10mmol/L then the SG values will be very inaccurate until the 3rd calibration.

So having the ising information in a NS pill (and a PO notification) when that "window" appears would be very much appreciated. Maybe it's time to create a new NS pill for "cgm" or "transmitter" which things like next calibration time and isig can be shown? Seems like this is not Medtronic specific and other CGMs could use it too.

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
