### ISSUE TITLE
"Poll due in XX seconds" does not work

### ISSUE THREAD

**Issue by GHNS** [pazaan/600SeriesAndroidUploader#237]
Extra polls due to expected sensor communication are ignored, the uploader just tries 5 minutes later (when sensor communications are expected again).

#### Your Environment

* Uploader Version Number: 0.6.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung Galaxy S4
* Android Version Number (e.g. use 4.4 for 4.4.4): 5.0.1
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): both
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.10.2-release-20171201

#### Brief Explanation of Issue
The issue appears sometimes when the polling interval of the uploader just fits the sensor reading of the pump (my guess).

I get a log message like
12:05:51: Please wait: Pump is expecting sensor communication. Poll due in 38 seconds
... but instead of polling again in 28 seconds, I get the next message 5 minutes later:
12:10:51: Please wait: Pump is expecting sensor communication. Poll due in 38 seconds
... and so on. The problem is, I never get a new reading until timing changes over time.

#### Steps to Reproduce (for bugs)
It just happens from time to time.

#### Severity Score
5 = Severe (potential impact on care), because I miss alerts

**Comment by Pogman** [comment]
This is not a uploader bug. Android 5.0.0 + 5.0.1 (e.g. Galaxy S4) has a device bug that causes them to not wake for a poll at the requested time and at some unspecified time that can clash with with pump-sensor comms.

The uploader will try and protect against radio clashes with the pump as there can be a risk of a lost sensor caused by broadcasting at the same time as the weaker sensor transmitter.

You can disable this protection via the 'advanced system settings' in the uploader and it will always process the poll request.

**Comment by GHNS** [comment]
Thanks, I will try that option. It will probably improve the situation.

**Comment by volkerrichert** [comment]
We use a S4 too. We upgrade it to the CM 13.0 (Android 6.0.1)

**Comment by volkerrichert** [comment]
This will fix that issue, too. We are running CM13 over a few years now.
