### ISSUE TITLE
`enteredBy` field missing from uploads

### ISSUE THREAD

**Issue by sulkaharo** [pazaan/600SeriesAndroidUploader#251]
For better Nightscout interoperability, please add a `enteredBy` field into the uploaded JSON for treatments, which would contain the same string as now uploaded for the `device` field in device statuses.

**Comment by Pogman** [comment]
The eneredBy field has been already been added for the next version and is in the beta.

The user has been given an option to partially name these too due to multiple / simultaneous uploader use. These use a header + serial or optional user value.

medtronic-600://1234-1234567
medtronic-600://Batman

**Comment by Pogman** [comment]
Closed - completed and available in 0.7.0 release
