### ISSUE TITLE
After migrating from mlab to mongodb (atlas) , upload no longer possible

### ISSUE THREAD

**Issue by mboterma670G** [pazaan/600SeriesAndroidUploader#278]
As MongoDB pulls the plug on the mlab plugin (10-Nov), I've migrated the code to cloud.mongodb.com (atlas).
However it seems that the loader doesn't work anymore. Generating the message;
Uploading to nightscout was unsuccessful. (device status) Internal Server Error.

#### Your Environment

* Uploader Version Number: 0.7.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): Nokia 1 Plus
* Android Version Number (e.g. use 4.4 for 4.4.4): 10 (00WW_2_10A_SP02)
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi and Mobile
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): Nightscout 13.0.1 Ketchup

#### Brief Explanation of Issue
occured when moving from heroku mlab plugin to cloud.mongodb.com. as per instruction on "https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/"

#### Uploader Error Code
Uploading to nightscout was unsuccessful. (device status) Internal Server Error.

#### Steps to Reproduce (for bugs)

1. Follow instructions on: "https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/"
2.
3.
4.

#### Severity Score
5 -> Use nightscout to monitor BG while driving my car (mirrored to iWatch), as you get fines driving a car when holding the medtronic 670G in your hands, to check your BG's. And driving without a clear understanding of your BG's is not smart.

**Comment by Pogman** [comment]
Try this guide: https://wolke.rueth.info/index.php/s/NjjgCF9rdbiWNbX#pdfviewer

**Comment by mboterma670G** [comment]
Hi, issue is not connecting Heroku to Atlas, that part is working fine. I can see that the app is populated with data from Atlas. 
Also tested the API response from the Atlas instance through SOAPUI. Also that part is working. However for some reason the uploader can't connect to Heroku to upload data.
I followed the instructions from Mongo. [https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/]

**Comment by pazaan** [comment]
The Uploader uses the Nightscout API, which is not dependent on whatever version/provider of MongoDB you have backing Nightscout. Are you able to view your data on Nightscout since the transition, and use the API Secret to manually log treatments to Nightscout?
If you can, then we'd need more specific instructions on how to reproduce (I personally am running Nightscout on my own VPS connected to Atlas).

**Comment by Pogman** [comment]
There are reports on the FB page of successful transition for 600 Series uploader users.

Another guide that may help: https://docs.google.com/document/d/1gV7dFeipTI3Fas246N10iAxQC8gETV5PIVfL31AYu_c/edit#heading=h.2xm1e0u2gzdc

**Comment by mboterma670G** [comment]
Hi Pazaan, i will veryfy and update you. Need to reconnect the site back to Atlas.

Hi Pogman, seems this one is more specific then the version from Atlas.

Thanks for your fast reply

**Comment by mboterma670G** [comment]
Update,

Set the MongoDB connection string again and all works like a charm. No clue why it is working now as I made a copy of the connection string yesterday and it failed. Did the same again today and now it's working.
Also the site is being updated by the uploader.
Great progress!!!!

Thanks to both

![image](https://user-images.githubusercontent.com/66777637/87763004-4756e680-c814-11ea-8ab8-10a14b0030f0.png)

**Comment by mboterma670G** [comment]
Not sure why it happened. entering the URL again solved the issue.

**Comment by galaviz-lip** [comment]
HI! I know the issue is closed, but now I have exactly the same problem after migrating to Atlas. My cell phone uploader cannot send any data the the DB. I can though upload svg values manually (and see them on the my NS site) using the script by:
https://github.com/cjo20/ns-api-uploader

I am not sure what really happened with the uploader. Any help is certainly appreciated. Thanks!

**Comment by galaviz-lip** [comment]
HI! I know the issue is closed, but now I have exactly the same problem after migrating to Atlas. My cell phone uploader cannot send any data the the DB. I can though upload svg values manually (and see them on the my NS site) using the script by:
https://github.com/cjo20/ns-api-uploader

I am not sure what really happened with the uploader. Any help is certainly appreciated. Thanks!

**Comment by galaviz-lip** [comment]
HI! I know the issue is closed, but now I have exactly the same problem after migrating to Atlas. My cell phone uploader cannot send any data the the DB. I can though upload svg values manually (and see them on the my NS site) using the script by:
https://github.com/cjo20/ns-api-uploader

I am not sure what really happened with the uploader. Any help is certainly appreciated. Thanks!

**Comment by Pogman** [comment]
The migration to Atlas is transparent to the uploader as the NS server handles the database.

Can you post a screenshot of the uploader log screen?

**Comment by galaviz-lip** [comment]
Thanks Pogman for the quick reply. 

I tried yesterday to upload the image, but I do not know why I was not able. Here it is:

I am really puzzled, as the uploader seems to not have any problems.

Thanks for the help!

Best,

Daniel
